openapi: 3.0.0
info:
    title: Jobs
    contact: {}
    version: "1.0"
servers:
    - url: http://localhost:5000/api/v1
      variables: {}
paths:
    /auth/register:
        post:
            tags:
                - Auth
            summary: register
            operationId: register
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/registerrequest"
                                - example:
                                      name: omar
                                      password: "123456"
                                      email: omar@gmail.com
                        example:
                            name: omar
                            password: "123456"
                            email: omar@gmail.com
                required: true
            responses:
                "200":
                    description: OK
                    headers:
                        X-Powered-By:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: Express
                        Content-Length:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: "185"
                        ETag:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: W/"b9-fwW/43EwOpD4fMWqkr6kBxL+rN8"
                        Date:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: Thu, 17 Aug 2023 10:36:36 GMT
                        Connection:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: keep-alive
                        Keep-Alive:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: timeout=5
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/GetAllproducts"
                                    - example:
                                          products:
                                              - featured: false
                                                rating: 4.6
                                                createdAt: 2023-08-17T09:22:33.920Z
                                                _id: 64dde6dc5832ae534a35bf4f
                                                name: bar stool
                                                price: 40
                                                company: liddy
                                                __v: 0
                                          nbHits: 1
                            example:
                                products:
                                    - featured: false
                                      rating: 4.6
                                      createdAt: 2023-08-17T09:22:33.920Z
                                      _id: 64dde6dc5832ae534a35bf4f
                                      name: bar stool
                                      price: 40
                                      company: liddy
                                      __v: 0
                                nbHits: 1
                "201":
                    description: Created
                    headers:
                        X-Powered-By:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: Express
                        Content-Length:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: "232"
                        ETag:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: W/"e8-S1YnK3d+D1dATTuKL20Kwq9jmvg"
                        Date:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: Tue, 22 Aug 2023 03:57:59 GMT
                        Connection:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: keep-alive
                        Keep-Alive:
                            content:
                                text/plain:
                                    schema:
                                        type: string
                                    example: timeout=5
                    content:
                        application/json; charset=utf-8:
                            schema:
                                allOf:
                                    - $ref: "#/components/schemas/register"
                                    - example:
                                          user:
                                              name: ragib
                                          token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGU0MzI0NjdiNzNhNjJlM2Q5ZWQ4ODYiLCJuYW1lIjoicmFnaWIiLCJpYXQiOjE2OTI2NzY2NzksImV4cCI6MTY5NTI2ODY3OX0.gwBDf5OiyT6FkPX0N0DBaarUFwVjXeEcG8ilUtUEQww
                            example:
                                user:
                                    name: ragib
                                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGU0MzI0NjdiNzNhNjJlM2Q5ZWQ4ODYiLCJuYW1lIjoicmFnaWIiLCJpYXQiOjE2OTI2NzY2NzksImV4cCI6MTY5NTI2ODY3OX0.gwBDf5OiyT6FkPX0N0DBaarUFwVjXeEcG8ilUtUEQww
            deprecated: false
            security: []
    /auth/login:
        post:
            tags:
                - Auth
            summary: Login
            operationId: Login
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/LoginRequest"
                                - example:
                                      email: omar@gmail.com
                                      password: "123456"
                        example:
                            email: omar@gmail.com
                            password: "123456"
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security: []
    /jobs:
        post:
            tags:
                - Jobs
            summary: Create Job
            operationId: CreateJob
            parameters: []
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/CreateJobRequest"
                                - example:
                                      company: Cefalo
                                      position: Full-time
                        example:
                            company: Cefalo
                            position: Full-time
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        get:
            tags:
                - Jobs
            summary: Get all jobs
            operationId: Getalljobs
            parameters: []
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
    /jobs/{id}:
        get:
            tags:
                - Jobs
            summary: Get a single job
            operationId: Getasinglejob
            parameters:
                - name: id
                  in: path
                  description: ""
                  required: true
                  style: simple
                  schema:
                      type: string
                      example: 64e58c0e78080a4c2c2289ea
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        patch:
            tags:
                - Jobs
            summary: Update job
            operationId: Updatejob
            parameters:
                - name: id
                  in: path
                  description: ""
                  required: true
                  style: simple
                  schema:
                      type: string
                      example: 64e58c0e78080a4c2c2289ea
            requestBody:
                description: ""
                content:
                    application/json:
                        schema:
                            allOf:
                                - $ref: "#/components/schemas/UpdatejobRequest"
                                - example:
                                      company: netflix
                                      position: back-end
                        example:
                            company: netflix
                            position: back-end
                required: true
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
        delete:
            tags:
                - Jobs
            summary: Delete Job
            operationId: DeleteJob
            parameters:
                - name: id
                  in: path
                  description: ""
                  required: true
                  style: simple
                  schema:
                      type: string
                      example: 64e58c0e78080a4c2c2289ea
            responses:
                "200":
                    description: ""
                    headers: {}
            deprecated: false
            security:
                - bearer: []
components:
    schemas:
        registerrequest:
            title: registerrequest
            required:
                - name
                - password
                - email
            type: object
            properties:
                name:
                    type: string
                password:
                    type: string
                email:
                    type: string
            example:
                name: omar
                password: "123456"
                email: omar@gmail.com
        GetAllproducts:
            title: GetAllproducts
            required:
                - products
                - nbHits
            type: object
            properties:
                products:
                    type: array
                    items:
                        $ref: "#/components/schemas/Product"
                    description: ""
                nbHits:
                    type: integer
                    format: int32
            example:
                products:
                    - featured: false
                      rating: 4.6
                      createdAt: 2023-08-17T09:22:33.920Z
                      _id: 64dde6dc5832ae534a35bf4f
                      name: bar stool
                      price: 40
                      company: liddy
                      __v: 0
                nbHits: 1
        Product:
            title: Product
            required:
                - featured
                - rating
                - createdAt
                - _id
                - name
                - price
                - company
                - __v
            type: object
            properties:
                featured:
                    type: boolean
                rating:
                    type: number
                createdAt:
                    type: string
                _id:
                    type: string
                name:
                    type: string
                price:
                    type: integer
                    format: int32
                company:
                    type: string
                __v:
                    type: integer
                    format: int32
            example:
                featured: false
                rating: 4.6
                createdAt: 2023-08-17T09:22:33.920Z
                _id: 64dde6dc5832ae534a35bf4f
                name: bar stool
                price: 40
                company: liddy
                __v: 0
        register:
            title: register
            required:
                - user
                - token
            type: object
            properties:
                user:
                    allOf:
                        - $ref: "#/components/schemas/User"
                        - {}
                token:
                    type: string
            example:
                user:
                    name: ragib
                token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGU0MzI0NjdiNzNhNjJlM2Q5ZWQ4ODYiLCJuYW1lIjoicmFnaWIiLCJpYXQiOjE2OTI2NzY2NzksImV4cCI6MTY5NTI2ODY3OX0.gwBDf5OiyT6FkPX0N0DBaarUFwVjXeEcG8ilUtUEQww
        User:
            title: User
            required:
                - name
            type: object
            properties:
                name:
                    type: string
            example:
                name: ragib
        LoginRequest:
            title: LoginRequest
            required:
                - email
                - password
            type: object
            properties:
                email:
                    type: string
                password:
                    type: string
            example:
                email: omar@gmail.com
                password: "123456"
        CreateJobRequest:
            title: CreateJobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: Cefalo
                position: Full-time
        UpdatejobRequest:
            title: UpdatejobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: netflix
                position: back-end
        DeleteJobRequest:
            title: DeleteJobRequest
            required:
                - company
                - position
            type: object
            properties:
                company:
                    type: string
                position:
                    type: string
            example:
                company: netflix
                position: back-end
    securitySchemes:
        bearer:
            type: http
            scheme: bearer
security: []
tags:
    - name: Auth
      description: ""
    - name: Jobs
      description: ""
